# Generated by Django 3.2.9 on 2021-12-07 14:51

from django.db import migrations
import django.db.models.deletion
import django.db.models.manager
import paper_uploads.models.fields.collection


class Migration(migrations.Migration):

    dependencies = [
        ('paper_uploads', '0007_alter_collection_options'),
        ('standard_collection', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StandardCollection',
        ),
        migrations.CreateModel(
            name='FilesOnlyCollection',
            fields=[
            ],
            options={
                'proxy': True,
                'default_permissions': (),
                'indexes': [],
                'constraints': [],
            },
            bases=('paper_uploads.collection',),
            managers=[
                ('default_mgr', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ImagesOnlyCollection',
            fields=[
            ],
            options={
                'proxy': True,
                'default_permissions': (),
                'indexes': [],
                'constraints': [],
            },
            bases=('paper_uploads.collection',),
            managers=[
                ('default_mgr', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='MixedCollection',
            fields=[
            ],
            options={
                'proxy': True,
                'default_permissions': (),
                'indexes': [],
                'constraints': [],
            },
            bases=('paper_uploads.collection',),
            managers=[
                ('default_mgr', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name='page',
            name='collection',
        ),
        migrations.AddField(
            model_name='page',
            name='file_collection',
            field=paper_uploads.models.fields.collection.CollectionField(on_delete=django.db.models.deletion.SET_NULL, to='standard_collection.filesonlycollection', verbose_name='file collection'),
        ),
        migrations.AddField(
            model_name='page',
            name='image_collection',
            field=paper_uploads.models.fields.collection.CollectionField(on_delete=django.db.models.deletion.SET_NULL, to='standard_collection.imagesonlycollection', verbose_name='image collection'),
        ),
        migrations.AddField(
            model_name='page',
            name='mixed_collection',
            field=paper_uploads.models.fields.collection.CollectionField(on_delete=django.db.models.deletion.SET_NULL, to='standard_collection.mixedcollection', verbose_name='mixed collection'),
        ),
    ]
