# Generated by Django 2.2.4 on 2019-08-29 14:54

from django.db import migrations
import django.db.models.deletion
import paper_uploads.models.fields.file
import paper_uploads.models.fields.collection
import paper_uploads.models.fields.image


class Migration(migrations.Migration):

    dependencies = [
        ('paper_uploads', '0001_initial'),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleGallery',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('paper_uploads.imagecollection',),
        ),
        migrations.AddField(
            model_name='page',
            name='file',
            field=paper_uploads.models.fields.file.FileField(blank=True, on_delete=django.db.models.deletion.SET_NULL, to='paper_uploads.UploadedFile', verbose_name='simple file'),
        ),
        migrations.AddField(
            model_name='page',
            name='image',
            field=paper_uploads.models.fields.image.ImageField(on_delete=django.db.models.deletion.SET_NULL, to='paper_uploads.UploadedImage', verbose_name='simple image'),
        ),
        migrations.AddField(
            model_name='page',
            name='image_ext',
            field=paper_uploads.models.fields.image.ImageField(on_delete=django.db.models.deletion.SET_NULL, to='paper_uploads.UploadedImage', verbose_name='image with variations'),
        ),
        migrations.AddField(
            model_name='page',
            name='gallery',
            field=paper_uploads.models.fields.collection.CollectionField(on_delete=django.db.models.deletion.SET_NULL, to='app.ArticleGallery', verbose_name='gallery'),
        ),
    ]
