# Generated by Django 4.0.1 on 2022-02-12 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_squashed_0028_alter_cloudinaryfileexample_file_size_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dummyversatileimageresource',
            old_name='file',
            new_name='image',
        ),
        migrations.AlterField(
            model_name='cloudinaryfileexample',
            name='name',
            field=models.CharField(max_length=128, verbose_name='name'),
        ),
    ]
