# Generated by Django 2.2.5 on 2019-10-01 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190928_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='page',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Page'),
        ),
    ]
