# Generated by Django 2.2.4 on 2019-08-30 07:34

from django.db import migrations
import django.db.models.deletion
import paper_uploads.models.fields.image


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190829_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='image',
            field=paper_uploads.models.fields.image.ImageField(blank=True, on_delete=django.db.models.deletion.SET_NULL, to='paper_uploads.UploadedImage', verbose_name='simple image'),
        ),
        migrations.AlterField(
            model_name='page',
            name='image_ext',
            field=paper_uploads.models.fields.image.ImageField(blank=True, on_delete=django.db.models.deletion.SET_NULL, to='paper_uploads.UploadedImage', verbose_name='image with variations'),
        ),
    ]
