# Generated by Django 3.0.9 on 2020-08-04 10:59

from django.db import migrations, models
import django.db.models.deletion
import paper_uploads.models.fields.image
import paper_uploads.validators


class Migration(migrations.Migration):

    dependencies = [
        ('paper_uploads', '0001_initial'),
        ('app', '0002_photocollection'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filefieldobject',
            options={'verbose_name': 'File', 'verbose_name_plural': 'Files'},
        ),
        migrations.CreateModel(
            name='ImageFieldObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', paper_uploads.models.fields.image.ImageField(blank=True, on_delete=django.db.models.deletion.SET_NULL, to='paper_uploads.UploadedImage', verbose_name='image')),
                ('image_extensions', paper_uploads.models.fields.image.ImageField(blank=True, help_text='Only `png` and `gif` allowed', on_delete=django.db.models.deletion.SET_NULL, to='paper_uploads.UploadedImage', validators=[paper_uploads.validators.ExtensionValidator(['.png', '.gif'])], verbose_name='Extension')),
                ('image_mimetypes', paper_uploads.models.fields.image.ImageField(blank=True, help_text='Only `image/png` and `image/jpeg` allowed', on_delete=django.db.models.deletion.SET_NULL, to='paper_uploads.UploadedImage', validators=[paper_uploads.validators.MimeTypeValidator(['image/png', 'image/jpeg'])], verbose_name='MimeType')),
                ('image_required', paper_uploads.models.fields.image.ImageField(on_delete=django.db.models.deletion.SET_NULL, to='paper_uploads.UploadedImage', verbose_name='required image')),
                ('image_size', paper_uploads.models.fields.image.ImageField(blank=True, help_text='Maximum file size is 64Kb', on_delete=django.db.models.deletion.SET_NULL, to='paper_uploads.UploadedImage', validators=[paper_uploads.validators.SizeValidator('64kb')], verbose_name='Size')),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'Images',
            },
        ),
    ]
