# Generated by Django 3.0.10 on 2020-09-27 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_filefieldobject_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagefieldobject',
            name='name',
            field=models.CharField(default='', max_length=128, verbose_name='name'),
            preserve_default=False,
        ),
    ]
