# Generated by Django 3.0.9 on 2020-08-04 11:01

from django.db import migrations
import django.db.models.deletion
import paper_uploads.models.fields.image
import paper_uploads.validators


class Migration(migrations.Migration):

    dependencies = [
        ('paper_uploads', '0001_initial'),
        ('app', '0003_auto_20200804_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagefieldobject',
            name='image_max_size',
            field=paper_uploads.models.fields.image.ImageField(blank=True, help_text='Image should be at most 1024x768 pixels', on_delete=django.db.models.deletion.SET_NULL, to='paper_uploads.UploadedImage', validators=[paper_uploads.validators.ImageMaxSizeValidator(1024, 768)], verbose_name='Max size'),
        ),
        migrations.AddField(
            model_name='imagefieldobject',
            name='image_min_size',
            field=paper_uploads.models.fields.image.ImageField(blank=True, help_text='Image should be at least 640x480 pixels', on_delete=django.db.models.deletion.SET_NULL, to='paper_uploads.UploadedImage', validators=[paper_uploads.validators.ImageMinSizeValidator(640, 480)], verbose_name='Min size'),
        ),
    ]
