# Generated by Django 3.1.8 on 2021-04-07 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_imagefieldobject_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='childfilecollection',
            options={'default_permissions': ()},
        ),
        migrations.AlterModelOptions(
            name='cloudinarycompletecollection',
            options={'default_permissions': ()},
        ),
        migrations.AlterModelOptions(
            name='cloudinaryfilecollection',
            options={'default_permissions': ()},
        ),
        migrations.AlterModelOptions(
            name='cloudinarymediacollection',
            options={'default_permissions': ()},
        ),
        migrations.AlterModelOptions(
            name='cloudinaryphotocollection',
            options={'default_permissions': ()},
        ),
        migrations.AlterModelOptions(
            name='completecollection',
            options={'default_permissions': ()},
        ),
        migrations.AlterModelOptions(
            name='dummyimagefieldresource',
            options={'default_permissions': ()},
        ),
        migrations.AlterModelOptions(
            name='dummyversatileimageresource',
            options={'default_permissions': ()},
        ),
        migrations.AlterModelOptions(
            name='filecollection',
            options={'default_permissions': ()},
        ),
        migrations.AlterModelOptions(
            name='isolatedfilecollection',
            options={'default_permissions': ()},
        ),
        migrations.AlterModelOptions(
            name='photocollection',
            options={'default_permissions': ()},
        ),
    ]
