# Generated by Django 3.0.9 on 2020-08-04 12:04

from django.db import migrations, models
import django.db.models.deletion
import paper_uploads.models.fields.collection


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200804_1101'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionFieldObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_collection', paper_uploads.models.fields.collection.CollectionField(on_delete=django.db.models.deletion.SET_NULL, to='app.FileCollection')),
                ('image_collection', paper_uploads.models.fields.collection.CollectionField(on_delete=django.db.models.deletion.SET_NULL, to='app.PhotoCollection')),
            ],
            options={
                'verbose_name': 'Collection',
                'verbose_name_plural': 'Collections',
            },
        ),
    ]
