# Generated by Django 2.2.4 on 2019-08-30 08:15

from django.db import migrations
import django.db.models.deletion
import paper_uploads.models.fields.gallery


class Migration(migrations.Migration):

    dependencies = [
        ('paper_uploads', '0002_uploadedfile_display_name'),
        ('app', '0004_auto_20190830_0809'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageFilesGallery',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('paper_uploads.gallery',),
        ),
        migrations.AlterField(
            model_name='page',
            name='gallery',
            field=paper_uploads.models.fields.gallery.CollectionField(on_delete=django.db.models.deletion.SET_NULL, to='app.PageGallery', verbose_name='image gallery'),
        ),
    ]
