# Generated by Django 3.0.9 on 2020-08-06 05:14

from django.db import migrations
import django.db.models.deletion
import paper_uploads.models.fields.collection


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_collectionfieldobject'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionfieldobject',
            name='full_collection',
            field=paper_uploads.models.fields.collection.CollectionField(on_delete=django.db.models.deletion.SET_NULL, to='app.CompleteCollection'),
        ),
    ]
