# Generated by Django 2.2.6 on 2019-10-24 10:14

from django.db import migrations
import django.db.models.deletion
import paper_uploads.models.fields.file


class Migration(migrations.Migration):

    dependencies = [
        ('paper_uploads_cloudinary', '0001_initial'),
        ('app', '0005_testcollection_testcollectionblocked_testcollectionoverride'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='cloud_image',
            field=paper_uploads.models.fields.file.FileField(on_delete=django.db.models.deletion.SET_NULL, to='paper_uploads_cloudinary.CloudinaryFile', verbose_name='cloud file'),
        ),
    ]
