# Generated by Django 3.0.8 on 2020-07-27 15:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_dummyversatileimageresource'),
    ]

    operations = [
        migrations.CreateModel(
            name='DummyReverseFieldResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(editable=False, help_text='human readable resource name', max_length=255, verbose_name='name')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='created at')),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='uploaded at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='changed at')),
                ('content_hash', models.CharField(editable=False, help_text='hash of the contents of a file', max_length=64, verbose_name='content hash')),
                ('extension', models.CharField(editable=False, help_text='Lowercase, without leading dot', max_length=32, verbose_name='extension')),
                ('size', models.PositiveIntegerField(default=0, editable=False, verbose_name='size')),
                ('owner_app_label', models.CharField(editable=False, max_length=100)),
                ('owner_model_name', models.CharField(editable=False, max_length=100)),
                ('owner_fieldname', models.CharField(editable=False, max_length=255)),
                ('file', models.FileField(upload_to='reverse_file', verbose_name='file')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='dummyfilefieldresource',
            name='file',
            field=models.FileField(upload_to='file_field', verbose_name='file'),
        ),
        migrations.AlterField(
            model_name='dummyimagefieldresource',
            name='file',
            field=models.FileField(upload_to='image_field', verbose_name='file'),
        ),
        migrations.AlterField(
            model_name='dummyversatileimageresource',
            name='file',
            field=models.FileField(upload_to='versatile_image', verbose_name='file'),
        ),
    ]
