# Generated by Django 3.0.9 on 2020-08-21 13:35

from django.db import migrations, models
import django.db.models.deletion
import paper_uploads.cloudinary.models.fields.file
import paper_uploads.cloudinary.models.fields.image
import paper_uploads.cloudinary.models.fields.media


class Migration(migrations.Migration):

    dependencies = [
        ('paper_uploads_cloudinary', '0001_initial'),
        ('app', '0006_collectionfieldobject_full_collection'),
    ]

    operations = [
        migrations.CreateModel(
            name='CloudinaryMediaExample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media', paper_uploads.cloudinary.models.fields.media.CloudinaryMediaField(on_delete=django.db.models.deletion.SET_NULL, to='paper_uploads_cloudinary.CloudinaryMedia', verbose_name='media')),
            ],
            options={
                'verbose_name': 'Cloudinary Media',
                'verbose_name_plural': 'Cloudinary Media',
            },
        ),
        migrations.CreateModel(
            name='CloudinaryImageExample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', paper_uploads.cloudinary.models.fields.image.CloudinaryImageField(on_delete=django.db.models.deletion.SET_NULL, to='paper_uploads_cloudinary.CloudinaryImage', verbose_name='image')),
            ],
            options={
                'verbose_name': 'Cloudinary Image',
                'verbose_name_plural': 'Cloudinary Images',
            },
        ),
        migrations.CreateModel(
            name='CloudinaryFileExample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', paper_uploads.cloudinary.models.fields.file.CloudinaryFileField(on_delete=django.db.models.deletion.SET_NULL, to='paper_uploads_cloudinary.CloudinaryFile', verbose_name='file')),
            ],
            options={
                'verbose_name': 'Cloudinary File',
                'verbose_name_plural': 'Cloudinary Files',
            },
        ),
    ]
