# Generated by Django 2.2.6 on 2019-10-24 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_page_cloud_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='cloud_image',
            new_name='cloud_file',
        ),
    ]
