# Generated by Django 2.2.5 on 2019-09-12 07:03

from django.db import migrations, models
import django.db.models.deletion
import paper_uploads.models.fields.gallery
import paper_uploads.models.fields.image


class Migration(migrations.Migration):

    dependencies = [
        ('paper_uploads', '0008_auto_20190911_1215'),
        ('app', '0006_page_files'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('files', paper_uploads.models.fields.gallery.CollectionField(on_delete=django.db.models.deletion.SET_NULL, to='app.PageFilesGallery', verbose_name='files')),
                ('image', paper_uploads.models.fields.image.ImageField(blank=True, on_delete=django.db.models.deletion.SET_NULL, to='paper_uploads.UploadedImage', verbose_name='simple image')),
            ],
            options={
                'verbose_name': 'document',
                'verbose_name_plural': 'documents',
            },
        ),
    ]
