# Generated by Django 3.2.6 on 2021-08-25 13:48

from django.db import migrations
import django.db.models.deletion
import paper_uploads.cloudinary.models.fields.image


class Migration(migrations.Migration):

    dependencies = [
        ('paper_uploads_cloudinary', '0002_auto_20210407_0627'),
        ('app', '0006_auto_20210708_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloudinaryimageexample',
            name='image_public',
            field=paper_uploads.cloudinary.models.fields.image.CloudinaryImageField(blank=True, on_delete=django.db.models.deletion.SET_NULL, to='paper_uploads_cloudinary.cloudinaryimage', verbose_name='Public image'),
        ),
    ]
