# Generated by Django 2.2.6 on 2019-11-06 05:17

from django.db import migrations
import django.db.models.deletion
import django.db.models.manager
import paper_uploads.models.fields.collection


class Migration(migrations.Migration):

    dependencies = [
        ('paper_uploads_cloudinary', '0002_cloudinarycollection_cloudinaryfileitem_cloudinaryimagecollection_cloudinaryimageitem_cloudinarymedi'),
        ('app', '0006_auto_20191105_0557'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageCloudinaryFilesGallery',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('paper_uploads_cloudinary.cloudinarycollection',),
            managers=[
                ('default_mgr', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='PageCloudinaryGallery',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('paper_uploads_cloudinary.cloudinaryimagecollection',),
            managers=[
                ('default_mgr', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='page',
            name='cloud_files',
            field=paper_uploads.models.fields.collection.CollectionField(on_delete=django.db.models.deletion.SET_NULL, to='app.PageCloudinaryFilesGallery', verbose_name='file gallery'),
        ),
        migrations.AddField(
            model_name='page',
            name='cloud_gallery',
            field=paper_uploads.models.fields.collection.CollectionField(on_delete=django.db.models.deletion.SET_NULL, to='app.PageCloudinaryGallery', verbose_name='image gallery'),
        ),
    ]
