# Generated by Django 2.2.6 on 2019-10-24 10:37

from django.db import migrations
import django.db.models.deletion
import paper_uploads.models.fields.file


class Migration(migrations.Migration):

    dependencies = [
        ('paper_uploads_cloudinary', '0002_cloudinaryimage'),
        ('app', '0007_auto_20191024_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='cloud_image',
            field=paper_uploads.models.fields.file.FileField(on_delete=django.db.models.deletion.SET_NULL, to='paper_uploads_cloudinary.CloudinaryImage', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='page',
            name='cloud_file',
            field=paper_uploads.models.fields.file.FileField(on_delete=django.db.models.deletion.SET_NULL, to='paper_uploads_cloudinary.CloudinaryFile', verbose_name='file'),
        ),
    ]
