# Generated by Django 3.0.8 on 2020-07-27 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20200727_1526'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DummyReadonlyFileResource',
            new_name='DummyReadonlyFileProxyResource',
        ),
    ]
