# Generated by Django 2.2.6 on 2019-12-20 20:17

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('paper_uploads', '0018_auto_20191102_0731'),
        ('app', '0007_auto_20191106_0517'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestCollection',
        ),
        migrations.DeleteModel(
            name='TestCollectionBlocked',
        ),
        migrations.DeleteModel(
            name='TestCollectionOverride',
        ),
        migrations.CreateModel(
            name='DummyCollection',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('paper_uploads.collection',),
            managers=[
                ('default_mgr', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='DummyCollectionBlocked',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('paper_uploads.collection',),
            managers=[
                ('default_mgr', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='DummyCollectionOverride',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('paper_uploads.collection',),
            managers=[
                ('default_mgr', django.db.models.manager.Manager()),
            ],
        ),
    ]
