# Generated by Django 3.0.9 on 2020-09-01 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_cloudinaryfileexample_cloudinaryimageexample_cloudinarymediaexample'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dummyresource',
            name='uploaded_at',
        ),
    ]
