# Generated by Django 2.2.5 on 2019-09-12 07:21

from django.db import migrations

def update_owner(apps, schema_editor, reverse=False):
    PageGallery = apps.get_model('app', 'PageGallery')
    for gallery in PageGallery._meta.base_manager.all():
        gallery.owner_app_label = gallery.owner_ct.app_label
        gallery.owner_model_name = gallery.owner_ct.model
        gallery.save()

    PageFilesGallery = apps.get_model('app', 'PageFilesGallery')
    for gallery in PageFilesGallery._meta.base_manager.all():
        gallery.owner_app_label = gallery.owner_ct.app_label
        gallery.owner_model_name = gallery.owner_ct.model
        gallery.save()


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20190912_0703'),
    ]

    operations = [
        migrations.RunPython(update_owner),
    ]
