# Generated by Django 3.0.8 on 2020-07-27 16:24

from django.db import migrations, models
import django.db.models.deletion
import paper_uploads.models.fields.file
import paper_uploads.models.fields.image


class Migration(migrations.Migration):

    dependencies = [
        ('paper_uploads', '0020_auto_20200723_1846'),
        ('app', '0008_auto_20200727_1535'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageExample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', paper_uploads.models.fields.image.ImageField(on_delete=django.db.models.deletion.SET_NULL, to='paper_uploads.UploadedImage', verbose_name='image')),
            ],
        ),
        migrations.CreateModel(
            name='FileExample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', paper_uploads.models.fields.file.FileField(on_delete=django.db.models.deletion.SET_NULL, to='paper_uploads.UploadedFile', verbose_name='file')),
            ],
        ),
    ]
