# Generated by Django 3.2.6 on 2021-09-07 05:30

from django.db import migrations
import django.db.models.deletion
import paper_uploads.models.fields.file


class Migration(migrations.Migration):

    dependencies = [
        ('paper_uploads', '0003_auto_20210906_1505'),
        ('app', '0008_auto_20210906_1505'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUploadedImage',
            fields=[
            ],
            options={
                'proxy': True,
                'default_permissions': (),
                'indexes': [],
                'constraints': [],
            },
            bases=('paper_uploads.uploadedimage',),
        ),
        migrations.AddField(
            model_name='imagefieldobject',
            name='image_custom',
            field=paper_uploads.models.fields.file.FileField(blank=True, on_delete=django.db.models.deletion.SET_NULL, to='app.customuploadedimage', verbose_name='custom image'),
        ),
    ]
