# Generated by Django 2.2.6 on 2019-10-24 10:52

from django.db import migrations
import django.db.models.deletion
import paper_uploads.models.fields.file
import paper_uploads.models.fields.image


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20191024_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='cloud_file',
            field=paper_uploads.models.fields.file.FileField(blank=True, on_delete=django.db.models.deletion.SET_NULL, to='paper_uploads_cloudinary.CloudinaryFile', verbose_name='file'),
        ),
        migrations.AlterField(
            model_name='page',
            name='cloud_image',
            field=paper_uploads.models.fields.image.ImageField(blank=True, on_delete=django.db.models.deletion.SET_NULL, to='paper_uploads_cloudinary.CloudinaryImage', verbose_name='image'),
        ),
    ]
