# Generated by Django 2.2.10 on 2020-02-19 20:05

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('paper_uploads', '0018_auto_20191102_0731'),
        ('app', '0008_auto_20191220_2017'),
    ]

    operations = [
        migrations.CreateModel(
            name='DummyCollectionSubclass',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('app.dummycollection',),
            managers=[
                ('default_mgr', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='DummyCollectionWithMeta',
            fields=[
            ],
            options={
                'verbose_name': 'gallery',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('paper_uploads.collection',),
            managers=[
                ('default_mgr', django.db.models.manager.Manager()),
            ],
        ),
    ]
