# Generated by Django 2.2.6 on 2019-10-25 04:47

from django.db import migrations
import django.db.models.deletion
import paper_uploads.cloudinary.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20191024_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='cloud_file',
            field=paper_uploads.cloudinary.models.fields.CloudinaryFileField(blank=True, on_delete=django.db.models.deletion.SET_NULL, to='paper_uploads_cloudinary.CloudinaryFile', verbose_name='file'),
        ),
        migrations.AlterField(
            model_name='page',
            name='cloud_image',
            field=paper_uploads.cloudinary.models.fields.CloudinaryImageField(blank=True, on_delete=django.db.models.deletion.SET_NULL, to='paper_uploads_cloudinary.CloudinaryImage', verbose_name='image'),
        ),
    ]
