# Generated by Django 3.0.9 on 2020-09-03 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_cloudinarycollectionfieldobject_cloudinarycompletecollection_cloudinaryfilecollection_cloudinarymedi'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cloudinarycollectionfieldobject',
            options={'verbose_name': 'Cloudinary Collection', 'verbose_name_plural': 'Cloudinary Collections'},
        ),
        migrations.RemoveField(
            model_name='dummyfilefieldresource',
            name='content_hash',
        ),
        migrations.RemoveField(
            model_name='dummyfileresource',
            name='content_hash',
        ),
        migrations.RemoveField(
            model_name='dummyimagefieldresource',
            name='content_hash',
        ),
        migrations.RemoveField(
            model_name='dummyversatileimageresource',
            name='content_hash',
        ),
        migrations.AddField(
            model_name='dummyfilefieldresource',
            name='checksum',
            field=models.CharField(default='', editable=False, max_length=64, verbose_name='checksum'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dummyfileresource',
            name='checksum',
            field=models.CharField(default='', editable=False, max_length=64, verbose_name='checksum'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dummyimagefieldresource',
            name='checksum',
            field=models.CharField(default='', editable=False, max_length=64, verbose_name='checksum'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dummyversatileimageresource',
            name='checksum',
            field=models.CharField(default='', editable=False, max_length=64, verbose_name='checksum'),
            preserve_default=False,
        ),
    ]
