# Generated by Django 3.2.6 on 2021-09-07 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20210907_0530'),
    ]

    operations = [
        migrations.AddField(
            model_name='isolatedfilecollection',
            name='name',
            field=models.CharField(blank=True, max_length=128, verbose_name='name'),
        ),
    ]
