# Generated by Django 3.2.6 on 2021-09-09 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20210909_0755'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionfieldobject',
            name='name',
            field=models.CharField(default='', max_length=128, verbose_name='name'),
            preserve_default=False,
        ),
    ]
