# Generated by Django 3.0.9 on 2020-09-07 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20200907_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dummyfilefieldresource',
            name='basename',
            field=models.CharField(editable=False, help_text='human-readable resource name', max_length=255, verbose_name='basename'),
        ),
        migrations.AlterField(
            model_name='dummyfileresource',
            name='basename',
            field=models.CharField(editable=False, help_text='human-readable resource name', max_length=255, verbose_name='basename'),
        ),
        migrations.AlterField(
            model_name='dummyimagefieldresource',
            name='basename',
            field=models.CharField(editable=False, help_text='human-readable resource name', max_length=255, verbose_name='basename'),
        ),
        migrations.AlterField(
            model_name='dummyresource',
            name='basename',
            field=models.CharField(editable=False, help_text='human-readable resource name', max_length=255, verbose_name='basename'),
        ),
        migrations.AlterField(
            model_name='dummyversatileimageresource',
            name='basename',
            field=models.CharField(editable=False, help_text='human-readable resource name', max_length=255, verbose_name='basename'),
        ),
    ]
