# Generated by Django 3.2.6 on 2021-09-10 11:12

from django.db import migrations
import django.db.models.deletion
import paper_uploads.cloudinary.models.fields.file
import paper_uploads.models.fields.image


class Migration(migrations.Migration):

    dependencies = [
        ('paper_uploads_cloudinary', '0003_delete_cloudinarycollection'),
        ('app', '0012_collectionfieldobject_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomCloudinaryFile',
            fields=[
            ],
            options={
                'proxy': True,
                'default_permissions': (),
                'indexes': [],
                'constraints': [],
            },
            bases=('paper_uploads_cloudinary.cloudinaryfile',),
        ),
        migrations.AlterField(
            model_name='imagefieldobject',
            name='image_custom',
            field=paper_uploads.models.fields.image.ImageField(blank=True, on_delete=django.db.models.deletion.SET_NULL, to='app.customuploadedimage', verbose_name='custom image'),
        ),
        migrations.AddField(
            model_name='cloudinaryfileexample',
            name='file_custom',
            field=paper_uploads.cloudinary.models.fields.file.CloudinaryFileField(blank=True, on_delete=django.db.models.deletion.SET_NULL, to='app.customcloudinaryfile', verbose_name='custom file'),
        ),
    ]
