# Generated by Django 3.0.9 on 2020-09-07 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20200907_1227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dummyresource',
            name='basename',
        ),
    ]
