# Generated by Django 2.2.6 on 2019-10-28 08:34

from django.db import migrations
import django.db.models.deletion
import django.db.models.manager
import paper_uploads.models.fields.collection


class Migration(migrations.Migration):

    dependencies = [
        ('paper_uploads', '0012_auto_20191025_1440'),
        ('app', '0012_auto_20191028_0719'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageCloudinaryFilesGallery',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('paper_uploads.collection',),
            managers=[
                ('default_mgr', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='page',
            name='cloud_files',
            field=paper_uploads.models.fields.collection.CollectionField(on_delete=django.db.models.deletion.SET_NULL, to='app.PageCloudinaryFilesGallery', verbose_name='file gallery'),
        ),
    ]
