# Generated by Django 3.2.9 on 2021-11-03 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paper_uploads', '0003_auto_20210906_1505'),
        ('app', '0014_auto_20210910_1221'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomImageItem',
        ),
        migrations.CreateModel(
            name='CustomProxyImageItem',
            fields=[
            ],
            options={
                'proxy': True,
                'default_permissions': (),
                'indexes': [],
                'constraints': [],
            },
            bases=('paper_uploads.imageitem',),
        ),
    ]
