# Generated by Django 3.2.9 on 2021-11-08 11:50

from django.db import migrations
import django.db.models.deletion
import django.db.models.manager
import paper_uploads.models.fields.collection


class Migration(migrations.Migration):

    dependencies = [
        ('paper_uploads', '0004_auto_20211106_1004'),
        ('app', '0016_customimageitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomProxyGallery',
            fields=[
            ],
            options={
                'proxy': True,
                'default_permissions': (),
                'indexes': [],
                'constraints': [],
            },
            bases=('paper_uploads.imagecollection',),
            managers=[
                ('default_mgr', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='collectionfieldobject',
            name='custom_proxy_collection',
            field=paper_uploads.models.fields.collection.CollectionField(on_delete=django.db.models.deletion.SET_NULL, to='app.customproxygallery'),
        ),
    ]
