# Generated by Django 3.2.9 on 2021-11-16 08:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20211108_1309'),
    ]

    operations = [
        migrations.CreateModel(
            name='DummyBacklinkResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_app_label', models.CharField(editable=False, max_length=100)),
                ('owner_model_name', models.CharField(editable=False, max_length=100)),
                ('owner_fieldname', models.CharField(editable=False, max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='changed at')),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.RemoveField(
            model_name='customcloudinaryimageitem',
            name='owner_app_label',
        ),
        migrations.RemoveField(
            model_name='customcloudinaryimageitem',
            name='owner_fieldname',
        ),
        migrations.RemoveField(
            model_name='customcloudinaryimageitem',
            name='owner_model_name',
        ),
        migrations.RemoveField(
            model_name='customimageitem',
            name='owner_app_label',
        ),
        migrations.RemoveField(
            model_name='customimageitem',
            name='owner_fieldname',
        ),
        migrations.RemoveField(
            model_name='customimageitem',
            name='owner_model_name',
        ),
        migrations.RemoveField(
            model_name='dummyfilefieldresource',
            name='owner_app_label',
        ),
        migrations.RemoveField(
            model_name='dummyfilefieldresource',
            name='owner_fieldname',
        ),
        migrations.RemoveField(
            model_name='dummyfilefieldresource',
            name='owner_model_name',
        ),
        migrations.RemoveField(
            model_name='dummyfileresource',
            name='owner_app_label',
        ),
        migrations.RemoveField(
            model_name='dummyfileresource',
            name='owner_fieldname',
        ),
        migrations.RemoveField(
            model_name='dummyfileresource',
            name='owner_model_name',
        ),
        migrations.RemoveField(
            model_name='dummyimagefieldresource',
            name='owner_app_label',
        ),
        migrations.RemoveField(
            model_name='dummyimagefieldresource',
            name='owner_fieldname',
        ),
        migrations.RemoveField(
            model_name='dummyimagefieldresource',
            name='owner_model_name',
        ),
        migrations.RemoveField(
            model_name='dummyresource',
            name='owner_app_label',
        ),
        migrations.RemoveField(
            model_name='dummyresource',
            name='owner_fieldname',
        ),
        migrations.RemoveField(
            model_name='dummyresource',
            name='owner_model_name',
        ),
        migrations.RemoveField(
            model_name='dummyversatileimageresource',
            name='owner_app_label',
        ),
        migrations.RemoveField(
            model_name='dummyversatileimageresource',
            name='owner_fieldname',
        ),
        migrations.RemoveField(
            model_name='dummyversatileimageresource',
            name='owner_model_name',
        ),
    ]
