# Generated by Django 3.2.9 on 2021-11-16 11:44

from django.db import migrations
import django.db.models.deletion
import paper_uploads.models.fields.file
import paper_uploads.models.fields.image


class Migration(migrations.Migration):

    dependencies = [
        ('paper_uploads', '0006_auto_20211116_0748'),
        ('app', '0019_auto_20211116_0812'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomUploadedFile',
            new_name='CustomProxyUploadedFile'
        ),
        migrations.RenameModel(
            old_name='CustomUploadedImage',
            new_name='CustomProxyUploadedImage',
        ),
        migrations.AlterField(
            model_name='filefieldobject',
            name='file_custom',
            field=paper_uploads.models.fields.file.FileField(blank=True, on_delete=django.db.models.deletion.SET_NULL, to='app.customproxyuploadedfile', verbose_name='custom file'),
        ),
        migrations.AlterField(
            model_name='imagefieldobject',
            name='image_custom',
            field=paper_uploads.models.fields.image.ImageField(blank=True, on_delete=django.db.models.deletion.SET_NULL, to='app.customproxyuploadedimage', verbose_name='custom image'),
        ),
    ]
