# Generated by Django 3.2.9 on 2021-11-16 12:10

from django.db import migrations
import django.db.models.deletion
import paper_uploads.models.fields.file
import paper_uploads.models.fields.image


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_auto_20211116_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filefieldobject',
            name='file_custom_proxy',
            field=paper_uploads.models.fields.file.FileField(blank=True, on_delete=django.db.models.deletion.SET_NULL, to='app.customproxyuploadedfile', verbose_name='custom proxy file'),
        ),
        migrations.AlterField(
            model_name='imagefieldobject',
            name='image_custom_proxy',
            field=paper_uploads.models.fields.image.ImageField(blank=True, on_delete=django.db.models.deletion.SET_NULL, to='app.customproxyuploadedimage', verbose_name='custom proxy image'),
        ),
    ]
