# Generated by Django 3.2.9 on 2021-12-07 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_auto_20211116_1210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filefieldobject',
            name='file',
        ),
        migrations.RemoveField(
            model_name='filefieldobject',
            name='file_custom',
        ),
        migrations.RemoveField(
            model_name='filefieldobject',
            name='file_custom_proxy',
        ),
        migrations.RemoveField(
            model_name='filefieldobject',
            name='file_extensions',
        ),
        migrations.RemoveField(
            model_name='filefieldobject',
            name='file_mimetypes',
        ),
        migrations.RemoveField(
            model_name='filefieldobject',
            name='file_required',
        ),
        migrations.RemoveField(
            model_name='filefieldobject',
            name='file_size',
        ),
        migrations.RemoveField(
            model_name='imagefieldobject',
            name='image',
        ),
        migrations.RemoveField(
            model_name='imagefieldobject',
            name='image_custom',
        ),
        migrations.RemoveField(
            model_name='imagefieldobject',
            name='image_custom_proxy',
        ),
        migrations.RemoveField(
            model_name='imagefieldobject',
            name='image_extensions',
        ),
        migrations.RemoveField(
            model_name='imagefieldobject',
            name='image_max_size',
        ),
        migrations.RemoveField(
            model_name='imagefieldobject',
            name='image_mimetypes',
        ),
        migrations.RemoveField(
            model_name='imagefieldobject',
            name='image_min_size',
        ),
        migrations.RemoveField(
            model_name='imagefieldobject',
            name='image_required',
        ),
        migrations.RemoveField(
            model_name='imagefieldobject',
            name='image_size',
        ),
        migrations.DeleteModel(
            name='CustomUploadedFile',
        ),
        migrations.DeleteModel(
            name='CustomUploadedImage',
        ),
        migrations.DeleteModel(
            name='CustomProxyUploadedFile',
        ),
        migrations.DeleteModel(
            name='CustomProxyUploadedImage',
        ),
        migrations.DeleteModel(
            name='FileFieldObject',
        ),
        migrations.DeleteModel(
            name='ImageFieldObject',
        ),
    ]
