# Generated by Django 3.2.9 on 2021-12-08 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_auto_20211207_1439'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collectionfieldobject',
            name='custom_collection',
        ),
        migrations.RemoveField(
            model_name='collectionfieldobject',
            name='custom_proxy_collection',
        ),
        migrations.RemoveField(
            model_name='collectionfieldobject',
            name='file_collection',
        ),
        migrations.RemoveField(
            model_name='collectionfieldobject',
            name='full_collection',
        ),
        migrations.RemoveField(
            model_name='collectionfieldobject',
            name='image_collection',
        ),
        migrations.RemoveField(
            model_name='isolatedfilecollection',
            name='collection_ptr',
        ),
        migrations.DeleteModel(
            name='ChildFileCollection',
        ),
        migrations.DeleteModel(
            name='FileCollection',
        ),
        migrations.DeleteModel(
            name='PhotoCollection',
        ),
        migrations.DeleteModel(
            name='CollectionFieldObject',
        ),
        migrations.DeleteModel(
            name='IsolatedFileCollection',
        ),
    ]
