# Generated by Django 3.2.9 on 2021-12-08 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_auto_20211208_1031'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompleteCollection',
        ),
    ]
