# Generated by Django 3.2.9 on 2021-12-08 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_delete_completecollection'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomGallery',
        ),
    ]
