# Generated by Django 3.2.9 on 2021-12-08 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_delete_customgallery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customimageitem',
            name='collectionitembase_ptr',
        ),
        migrations.DeleteModel(
            name='CustomProxyGallery',
        ),
        migrations.DeleteModel(
            name='CustomProxyImageItem',
        ),
        migrations.DeleteModel(
            name='CustomImageItem',
        ),
    ]
