language: python
python:
  - 3.9
  - 3.8
  - 3.7
  - 3.6
before_install:
  - nvm install 15
  - node --version
  - npm ci
  - pip install -U pip setuptools wheel tox-travis
  - pip install twine
  - pip install -r ./requirements.txt
  - npx webpack --mode=production
branches:
  only:
    - master
    - dev
    - "/^v?\\d(\\.\\d+)+$/"
script:
  - python setup.py sdist
  - python setup.py bdist_wheel
  - twine check dist/*
  - tox -- -n auto
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  skip_existing: true
  skip_cleanup: true
  user: __token__
  password:
    secure: B7rzqf67Lc/AnnOV9UB6ICe378e6FScqFGrB2VdpVfOYfKyDZv0/A5IOlKmSKBv0WDE08PqTHym7dqgFEAAz12MlYCxok5NGpOJtZN1WRVb7PYQM8oMUcIIj2gAF7vp+l9/NJ2U3dawkMRsj2MXcVNOYyb3yxm79B+tkvggaNSomJPnN+9a0F+/7NKEqflLI4/Rqi2KvxVtPD6TouSr6/JSCksjUEHmyfiiM+Q/O/0aeVlyT7BONx3OQkM2XVa5vuN+Lt3w3GkVb0XI3DZrhNh7bZOHltBQqoHmekBPl3PDFY+fTnqWNUwwOMVxtB+BQPzZml7sK2b5czezo4oyQGKomAl5hpQoX/vqeSwrvV5Dg3S/OFXXPrffT7P/lKNx/4elhQPty3RUV0HgOa9RHxgEiUNbD1WrUuMPTRBHK5fKsfA1CYZOUvF8xZVoRwj+0HdxjIM8gLf/xVFnR2iv/Plt3y+l7yyafGyM1iCstx6DdcFxEfV6IThc3dbxlzfbMzIGDHWei2D2KU5VOCkpdnJw/BPzKzyIyEva3j3CWwPgzdbpCdoPOJs6o6mREEmoA4NbA9K+oNKTqGAqOFx/svzcv5bAV9WBANPcITSItTWcw5tUDDQNP6kLZUkW6yBBnPowxtVnl2vz7leOPfH3zk2A1YU/71YDzUCAOm/UCK74=
  on:
    repo: dldevinc/paper-uploads
    condition: "$TRAVIS_PYTHON_VERSION = 3.8"
    tags: true
