# Generated by Django 4.0.1 on 2022-02-16 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_models_fields', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuploadedfile',
            old_name='basename',
            new_name='resource_name',
        ),
        migrations.RenameField(
            model_name='customuploadedimage',
            old_name='basename',
            new_name='resource_name',
        ),
    ]
