# Generated by Django 4.0.2 on 2022-02-09 09:24

from django.db import migrations, models
import django.db.models.deletion
import paper_uploads.models.fields.file
import paper_uploads.models.fields.image
import storages.backends.dropbox


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('paper_uploads', '0001_squashed_0009_alter_collectionitembase_polymorphic_ctype_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', paper_uploads.models.fields.file.FileField(blank=True, on_delete=django.db.models.deletion.SET_NULL, storage=storages.backends.dropbox.DropBoxStorage(), to='paper_uploads.uploadedfile', upload_to='files', verbose_name='file')),
                ('image', paper_uploads.models.fields.image.ImageField(blank=True, on_delete=django.db.models.deletion.SET_NULL, storage=storages.backends.dropbox.DropBoxStorage(), to='paper_uploads.uploadedimage', upload_to='images', verbose_name='image')),
            ],
            options={
                'verbose_name': 'Page',
            },
        ),
    ]
