# Generated by Django 4.0.2 on 2022-03-25 10:15

from django.db import migrations
import django.db.models.deletion
import paper_uploads.models.fields.svg


class Migration(migrations.Migration):

    dependencies = [
        ('paper_uploads', '0007_uploadedsvgfile'),
        ('standard_fields', '0002_page_image_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='svg',
            field=paper_uploads.models.fields.svg.SVGFileField(blank=True, on_delete=django.db.models.deletion.SET_NULL, storage=None, to='paper_uploads.uploadedsvgfile', upload_to='', verbose_name='svg'),
        ),
    ]
