# Generated by Django 3.2.9 on 2021-12-08 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_collection_item', '0002_auto_20211208_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='customimageitem',
            name='caption',
            field=models.TextField(blank=True, verbose_name='caption'),
        ),
    ]
