# Generated by Django 4.0.2 on 2022-02-09 05:39

from django.db import migrations
import paper_uploads.models.fields.base


class Migration(migrations.Migration):

    dependencies = [
        ('custom_files', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuploadedfile',
            name='file',
            field=paper_uploads.models.fields.base.DynamicStorageFileField(verbose_name='file'),
        ),
    ]
