# Generated by Django 4.0.2 on 2022-02-09 09:26

from django.db import migrations, models
import django.db.models.deletion
import paper_uploads.models.fields.file
import paper_uploads.models.fields.image


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('paper_uploads', '0001_squashed_0009_alter_collectionitembase_polymorphic_ctype_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFileProxy',
            fields=[
            ],
            options={
                'proxy': True,
                'default_permissions': (),
                'indexes': [],
                'constraints': [],
            },
            bases=('paper_uploads.uploadedfile',),
        ),
        migrations.CreateModel(
            name='UploadedImageProxy',
            fields=[
            ],
            options={
                'proxy': True,
                'default_permissions': (),
                'indexes': [],
                'constraints': [],
            },
            bases=('paper_uploads.uploadedimage',),
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', paper_uploads.models.fields.file.FileField(blank=True, on_delete=django.db.models.deletion.SET_NULL, storage=None, to='proxy_models_fields.uploadedfileproxy', upload_to='', verbose_name='file')),
                ('image', paper_uploads.models.fields.image.ImageField(blank=True, on_delete=django.db.models.deletion.SET_NULL, storage=None, to='proxy_models_fields.uploadedimageproxy', upload_to='', verbose_name='image')),
            ],
            options={
                'verbose_name': 'Page',
            },
        ),
    ]
