# Generated by Django 3.2.12 on 2022-02-21 09:44

from django.db import migrations
import django.db.models.deletion
import paper_uploads.models.fields.file


class Migration(migrations.Migration):

    dependencies = [
        ('paper_uploads', '0005_collection_modified_at'),
        ('proxy_models_fields', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUploadedFileProxy',
            fields=[
            ],
            options={
                'proxy': True,
                'default_permissions': (),
                'indexes': [],
                'constraints': [],
            },
            bases=('paper_uploads.uploadedfile',),
        ),
        migrations.AddField(
            model_name='page',
            name='custom_file',
            field=paper_uploads.models.fields.file.FileField(blank=True, on_delete=django.db.models.deletion.SET_NULL, storage=None, to='proxy_models_fields.customuploadedfileproxy', upload_to='', verbose_name='custom file'),
        ),
    ]
