# Generated by Django 4.0.1 on 2022-02-17 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_models_collections', '0003_alter_imageitem_resource_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageitem',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='imageitem',
            name='modified_at',
        ),
    ]
