# Generated by Django 4.2.8 on 2023-12-21 13:19

from django.db import migrations
import django.db.models.deletion
import django.db.models.manager
import paper_uploads.models.fields.collection


class Migration(migrations.Migration):

    dependencies = [
        ('paper_uploads', '0013_configurableimageitem'),
        ('validators_collections', '0002_alter_page_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
            ],
            options={
                'proxy': True,
                'default_permissions': (),
                'indexes': [],
                'constraints': [],
            },
            bases=('paper_uploads.imagecollection',),
            managers=[
                ('default_mgr', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='page',
            name='collection',
            field=paper_uploads.models.fields.collection.CollectionField(on_delete=django.db.models.deletion.SET_NULL, storage=None, to='validators_collections.mixedcollection', upload_to='', verbose_name='mixed collection'),
        ),
        migrations.AddField(
            model_name='page',
            name='gallery',
            field=paper_uploads.models.fields.collection.CollectionField(on_delete=django.db.models.deletion.SET_NULL, storage=None, to='validators_collections.gallery', upload_to='', verbose_name='gallery'),
        ),
    ]
