# Generated by Django 2.2.4 on 2019-08-29 14:53

import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('upload', 'Can upload files'), ('change', 'Can change files'), ('delete', 'Can delete files')),
                'managed': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='GalleryItemBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.IntegerField()),
                ('item_type', models.CharField(db_index=True, editable=False, max_length=32, verbose_name='type')),
                ('order', models.IntegerField(default=0, editable=False, verbose_name='order')),
                ('content_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_paper_uploads.galleryitembase_set+', to='contenttypes.ContentType')),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='file name')),
                ('extension', models.CharField(blank=True, max_length=32, verbose_name='file extension')),
                ('size', models.PositiveIntegerField(default=0, editable=False, verbose_name='file size')),
                ('hash', models.CharField(editable=False, help_text='SHA-1 hash of the file contents', max_length=40, verbose_name='file hash')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='created at')),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='uploaded at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='changed at')),
                ('file', models.FileField(max_length=255, storage=django.core.files.storage.FileSystemStorage(), upload_to='files/%Y-%m-%d', verbose_name='file')),
            ],
            options={
                'verbose_name': 'file',
                'verbose_name_plural': 'files',
                'abstract': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='GalleryFileItem',
            fields=[
                ('galleryitembase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='paper_uploads.GalleryItemBase')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='file name')),
                ('extension', models.CharField(blank=True, max_length=32, verbose_name='file extension')),
                ('size', models.PositiveIntegerField(default=0, editable=False, verbose_name='file size')),
                ('hash', models.CharField(editable=False, help_text='SHA-1 hash of the file contents', max_length=40, verbose_name='file hash')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='created at')),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='uploaded at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='changed at')),
                ('file', models.FileField(max_length=255, storage=django.core.files.storage.FileSystemStorage(), upload_to='gallery/files/%Y-%m-%d', verbose_name='file')),
                ('preview', models.CharField(blank=True, editable=False, max_length=255, verbose_name='preview URL')),
            ],
            options={
                'verbose_name': 'file',
                'verbose_name_plural': 'files',
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('paper_uploads.galleryitembase', models.Model),
        ),
        migrations.CreateModel(
            name='GalleryImageItem',
            fields=[
                ('galleryitembase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='paper_uploads.GalleryItemBase')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='file name')),
                ('extension', models.CharField(blank=True, max_length=32, verbose_name='file extension')),
                ('size', models.PositiveIntegerField(default=0, editable=False, verbose_name='file size')),
                ('hash', models.CharField(editable=False, help_text='SHA-1 hash of the file contents', max_length=40, verbose_name='file hash')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='created at')),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='uploaded at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='changed at')),
                ('width', models.PositiveSmallIntegerField(default=0, editable=False, verbose_name='width')),
                ('height', models.PositiveSmallIntegerField(default=0, editable=False, verbose_name='height')),
                ('cropregion', models.CharField(blank=True, editable=False, max_length=24, verbose_name='crop region')),
                ('alt', models.CharField(blank=True, help_text='This text will be used by screen readers, search engines, or when the image cannot be loaded', max_length=255, verbose_name='alternate text')),
                ('title', models.CharField(blank=True, help_text='The title is used as a tooltip when the user hovers the mouse over the image', max_length=255, verbose_name='title')),
                ('file', models.FileField(max_length=255, storage=django.core.files.storage.FileSystemStorage(), upload_to='gallery/images/%Y-%m-%d', verbose_name='file')),
            ],
            options={
                'verbose_name': 'image',
                'verbose_name_plural': 'images',
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('paper_uploads.galleryitembase', models.Model),
        ),
        migrations.CreateModel(
            name='GallerySVGItem',
            fields=[
                ('galleryitembase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='paper_uploads.GalleryItemBase')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='file name')),
                ('extension', models.CharField(blank=True, max_length=32, verbose_name='file extension')),
                ('size', models.PositiveIntegerField(default=0, editable=False, verbose_name='file size')),
                ('hash', models.CharField(editable=False, help_text='SHA-1 hash of the file contents', max_length=40, verbose_name='file hash')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='created at')),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='uploaded at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='changed at')),
                ('file', models.FileField(max_length=255, storage=django.core.files.storage.FileSystemStorage(), upload_to='gallery/files/%Y-%m-%d', verbose_name='file')),
            ],
            options={
                'verbose_name': 'SVG-file',
                'verbose_name_plural': 'SVG-files',
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('paper_uploads.galleryitembase', models.Model),
        ),
        migrations.CreateModel(
            name='UploadedImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='file name')),
                ('extension', models.CharField(blank=True, max_length=32, verbose_name='file extension')),
                ('size', models.PositiveIntegerField(default=0, editable=False, verbose_name='file size')),
                ('hash', models.CharField(editable=False, help_text='SHA-1 hash of the file contents', max_length=40, verbose_name='file hash')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='created at')),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='uploaded at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='changed at')),
                ('width', models.PositiveSmallIntegerField(default=0, editable=False, verbose_name='width')),
                ('height', models.PositiveSmallIntegerField(default=0, editable=False, verbose_name='height')),
                ('cropregion', models.CharField(blank=True, editable=False, max_length=24, verbose_name='crop region')),
                ('alt', models.CharField(blank=True, help_text='This text will be used by screen readers, search engines, or when the image cannot be loaded', max_length=255, verbose_name='alternate text')),
                ('title', models.CharField(blank=True, help_text='The title is used as a tooltip when the user hovers the mouse over the image', max_length=255, verbose_name='title')),
                ('file', models.FileField(max_length=255, storage=django.core.files.storage.FileSystemStorage(), upload_to='images/%Y-%m-%d', verbose_name='file')),
                ('owner_fieldname', models.CharField(editable=False, max_length=255)),
                ('owner_ct', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contenttypes.ContentType')),
            ],
            options={
                'verbose_name': 'image',
                'verbose_name_plural': 'images',
                'abstract': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_fieldname', models.CharField(editable=False, max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='created at')),
                ('gallery_content_type', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.ContentType', verbose_name='gallery type')),
                ('owner_ct', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contenttypes.ContentType')),
                ('cover', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='paper_uploads.GalleryImageItem', verbose_name='cover image')),
            ],
            options={
                'verbose_name': 'gallery',
                'verbose_name_plural': 'galleries',
                'abstract': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='ImageGallery',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('paper_uploads.gallery',),
        ),
    ]
