# Generated by Django 2.2.5 on 2019-09-27 13:16

import django.core.files.storage
from django.db import migrations, models
import django.db.migrations.operations.special
import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
import paper_uploads.models.image


# Functions from the following migrations need manual copying.
# Move them and any dependencies into this file, then update the
# RunPython operations to refer to the local versions:
# paper_uploads.migrations.0006_auto_20190911_1204

class Migration(migrations.Migration):

    replaces = [('paper_uploads', '0001_initial'), ('paper_uploads', '0002_uploadedfile_display_name'), ('paper_uploads', '0003_galleryfileitem_display_name'), ('paper_uploads', '0004_gallerysvgitem_display_name'), ('paper_uploads', '0005_auto_20190911_1204'), ('paper_uploads', '0006_auto_20190911_1204'), ('paper_uploads', '0007_remove_uploadedimage_owner_ct'), ('paper_uploads', '0008_auto_20190911_1215'), ('paper_uploads', '0009_remove_gallery_owner_ct'), ('paper_uploads', '0010_auto_20190912_0854'), ('paper_uploads', '0011_auto_20190916_1514'), ('paper_uploads', '0012_auto_20190918_1250'), ('paper_uploads', '0013_auto_20190924_1350'), ('paper_uploads', '0014_auto_20190927_0623'), ('paper_uploads', '0015_auto_20190927_0624'), ('paper_uploads', '0016_auto_20190927_0625'), ('paper_uploads', '0017_auto_20190927_0633'), ('paper_uploads', '0018_auto_20190927_0635')]

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('upload', 'Can upload files'), ('change', 'Can change files'), ('delete', 'Can delete files')),
                'managed': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='GalleryItemBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.IntegerField()),
                ('item_type', models.CharField(db_index=True, editable=False, max_length=32, verbose_name='type')),
                ('order', models.IntegerField(default=0, editable=False, verbose_name='order')),
                ('content_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_paper_uploads.galleryitembase_set+', to='contenttypes.ContentType')),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='GalleryImageItem',
            fields=[
                ('galleryitembase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='paper_uploads.GalleryItemBase')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='file name')),
                ('extension', models.CharField(blank=True, max_length=32, verbose_name='file extension')),
                ('size', models.PositiveIntegerField(default=0, editable=False, verbose_name='file size')),
                ('hash', models.CharField(editable=False, help_text='SHA-1 hash of the file contents', max_length=40, verbose_name='file hash')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='created at')),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='uploaded at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='changed at')),
                ('width', models.PositiveSmallIntegerField(default=0, editable=False, verbose_name='width')),
                ('height', models.PositiveSmallIntegerField(default=0, editable=False, verbose_name='height')),
                ('cropregion', models.CharField(blank=True, editable=False, max_length=24, verbose_name='crop region')),
                ('alt', models.CharField(blank=True, help_text='This text will be used by screen readers, search engines, or when the image cannot be loaded', max_length=255, verbose_name='alternate text')),
                ('title', models.CharField(blank=True, help_text='The title is used as a tooltip when the user hovers the mouse over the image', max_length=255, verbose_name='title')),
                ('file', models.FileField(max_length=255, storage=django.core.files.storage.FileSystemStorage(), upload_to='gallery/images/%Y-%m-%d', verbose_name='file')),
            ],
            options={
                'verbose_name': 'image',
                'verbose_name_plural': 'images',
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('paper_uploads.galleryitembase', models.Model),
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_fieldname', models.CharField(editable=False, max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='created at')),
                ('gallery_content_type', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.ContentType', verbose_name='gallery type')),
                ('owner_ct', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contenttypes.ContentType')),
                ('cover', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='paper_uploads.GalleryImageItem', verbose_name='cover image')),
            ],
            options={
                'verbose_name': 'gallery',
                'verbose_name_plural': 'galleries',
                'abstract': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='ImageCollection',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('paper_uploads.gallery',),
        ),
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='file name')),
                ('extension', models.CharField(blank=True, max_length=32, verbose_name='file extension')),
                ('size', models.PositiveIntegerField(default=0, editable=False, verbose_name='file size')),
                ('hash', models.CharField(editable=False, help_text='SHA-1 hash of the file contents', max_length=40, verbose_name='file hash')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='created at')),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='uploaded at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='changed at')),
                ('file', models.FileField(max_length=255, storage=django.core.files.storage.FileSystemStorage(), upload_to='files/%Y-%m-%d', verbose_name='file')),
                ('display_name', models.CharField(blank=True, max_length=255, verbose_name='display name')),
            ],
            options={
                'verbose_name': 'file',
                'verbose_name_plural': 'files',
                'abstract': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='GalleryFileItem',
            fields=[
                ('galleryitembase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='paper_uploads.GalleryItemBase')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='file name')),
                ('extension', models.CharField(blank=True, max_length=32, verbose_name='file extension')),
                ('size', models.PositiveIntegerField(default=0, editable=False, verbose_name='file size')),
                ('hash', models.CharField(editable=False, help_text='SHA-1 hash of the file contents', max_length=40, verbose_name='file hash')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='created at')),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='uploaded at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='changed at')),
                ('file', models.FileField(max_length=255, storage=django.core.files.storage.FileSystemStorage(), upload_to='gallery/files/%Y-%m-%d', verbose_name='file')),
                ('preview', models.CharField(blank=True, editable=False, max_length=255, verbose_name='preview URL')),
                ('display_name', models.CharField(blank=True, max_length=255, verbose_name='display name')),
            ],
            options={
                'verbose_name': 'file',
                'verbose_name_plural': 'files',
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('paper_uploads.galleryitembase', models.Model),
        ),
        migrations.CreateModel(
            name='GallerySVGItem',
            fields=[
                ('galleryitembase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='paper_uploads.GalleryItemBase')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='file name')),
                ('extension', models.CharField(blank=True, max_length=32, verbose_name='file extension')),
                ('size', models.PositiveIntegerField(default=0, editable=False, verbose_name='file size')),
                ('hash', models.CharField(editable=False, help_text='SHA-1 hash of the file contents', max_length=40, verbose_name='file hash')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='created at')),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='uploaded at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='changed at')),
                ('file', models.FileField(max_length=255, storage=django.core.files.storage.FileSystemStorage(), upload_to='gallery/files/%Y-%m-%d', verbose_name='file')),
                ('display_name', models.CharField(blank=True, max_length=255, verbose_name='display name')),
            ],
            options={
                'verbose_name': 'SVG-file',
                'verbose_name_plural': 'SVG-files',
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('paper_uploads.galleryitembase', models.Model),
        ),
        migrations.CreateModel(
            name='UploadedImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='file name')),
                ('extension', models.CharField(blank=True, max_length=32, verbose_name='file extension')),
                ('size', models.PositiveIntegerField(default=0, editable=False, verbose_name='file size')),
                ('hash', models.CharField(editable=False, help_text='SHA-1 hash of the file contents', max_length=40, verbose_name='file hash')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='created at')),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='uploaded at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='changed at')),
                ('width', models.PositiveSmallIntegerField(default=0, editable=False, verbose_name='width')),
                ('height', models.PositiveSmallIntegerField(default=0, editable=False, verbose_name='height')),
                ('cropregion', models.CharField(blank=True, editable=False, max_length=24, verbose_name='crop region')),
                ('alt', models.CharField(blank=True, help_text='This text will be used by screen readers, search engines, or when the image cannot be loaded', max_length=255, verbose_name='alternate text')),
                ('title', models.CharField(blank=True, help_text='The title is used as a tooltip when the user hovers the mouse over the image', max_length=255, verbose_name='title')),
                ('file', models.FileField(max_length=255, storage=django.core.files.storage.FileSystemStorage(), upload_to='images/%Y-%m-%d', verbose_name='file')),
                ('owner_fieldname', models.CharField(editable=False, max_length=255)),
                ('owner_ct', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contenttypes.ContentType')),
                ('owner_app_label', models.CharField(default='', editable=False, max_length=100)),
                ('owner_model_name', models.CharField(default='', editable=False, max_length=100)),
            ],
            options={
                'verbose_name': 'image',
                'verbose_name_plural': 'images',
                'abstract': False,
                'default_permissions': (),
            },
        ),
        migrations.RemoveField(
            model_name='uploadedimage',
            name='owner_ct',
        ),
        migrations.AddField(
            model_name='gallery',
            name='owner_app_label',
            field=models.CharField(default='', editable=False, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gallery',
            name='owner_model_name',
            field=models.CharField(default='', editable=False, max_length=100),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='owner_ct',
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='owner_app_label',
            field=models.CharField(default='', editable=False, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='owner_fieldname',
            field=models.CharField(default='', editable=False, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='owner_model_name',
            field=models.CharField(default='', editable=False, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='galleryfileitem',
            name='extension',
            field=models.CharField(editable=False, help_text='Lowercase string without leading dot', max_length=32, verbose_name='file extension'),
        ),
        migrations.AlterField(
            model_name='galleryimageitem',
            name='extension',
            field=models.CharField(editable=False, help_text='Lowercase string without leading dot', max_length=32, verbose_name='file extension'),
        ),
        migrations.AlterField(
            model_name='gallerysvgitem',
            name='extension',
            field=models.CharField(editable=False, help_text='Lowercase string without leading dot', max_length=32, verbose_name='file extension'),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='extension',
            field=models.CharField(editable=False, help_text='Lowercase string without leading dot', max_length=32, verbose_name='file extension'),
        ),
        migrations.AlterField(
            model_name='uploadedimage',
            name='extension',
            field=models.CharField(editable=False, help_text='Lowercase string without leading dot', max_length=32, verbose_name='file extension'),
        ),
        migrations.AlterModelOptions(
            name='gallery',
            options={'default_manager_name': 'default_mgr'},
        ),
        migrations.AlterModelManagers(
            name='gallery',
            managers=[
                ('default_mgr', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='galleryimageitem',
            name='file',
            field=paper_uploads.models.image.VariationalFileField(max_length=255, storage=django.core.files.storage.FileSystemStorage(), upload_to='gallery/images/%Y-%m-%d', verbose_name='file'),
        ),
        migrations.AlterField(
            model_name='uploadedimage',
            name='file',
            field=paper_uploads.models.image.VariationalFileField(max_length=255, storage=django.core.files.storage.FileSystemStorage(), upload_to='images/%Y-%m-%d', verbose_name='file'),
        ),
        migrations.RenameModel(
            old_name='GalleryFileItem',
            new_name='FileItem',
        ),
        migrations.RenameModel(
            old_name='GallerySVGItem',
            new_name='SVGItem',
        ),
        migrations.RenameModel(
            old_name='GalleryImageItem',
            new_name='ImageItem',
        ),
        migrations.RenameField(
            model_name='gallery',
            old_name='gallery_content_type',
            new_name='collection_content_type',
        ),
        migrations.AlterField(
            model_name='gallery',
            name='collection_content_type',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.ContentType'),
        ),
    ]
