# Generated by Django 2.2.5 on 2019-09-27 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper_uploads', '0001_squashed_0018_auto_20190927_0635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedimage',
            name='owner_app_label',
            field=models.CharField(editable=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='uploadedimage',
            name='owner_model_name',
            field=models.CharField(editable=False, max_length=100),
        ),
    ]
