# Generated by Django 3.0.9 on 2020-09-03 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper_uploads', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileitem',
            name='content_hash',
        ),
        migrations.RemoveField(
            model_name='imageitem',
            name='content_hash',
        ),
        migrations.RemoveField(
            model_name='svgitem',
            name='content_hash',
        ),
        migrations.RemoveField(
            model_name='uploadedfile',
            name='content_hash',
        ),
        migrations.RemoveField(
            model_name='uploadedimage',
            name='content_hash',
        ),
        migrations.AddField(
            model_name='fileitem',
            name='checksum',
            field=models.CharField(default='', editable=False, max_length=64, verbose_name='checksum'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imageitem',
            name='checksum',
            field=models.CharField(default='', editable=False, max_length=64, verbose_name='checksum'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='svgitem',
            name='checksum',
            field=models.CharField(default='', editable=False, max_length=64, verbose_name='checksum'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='checksum',
            field=models.CharField(default='', editable=False, max_length=64, verbose_name='checksum'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uploadedimage',
            name='checksum',
            field=models.CharField(default='', editable=False, max_length=64, verbose_name='checksum'),
            preserve_default=False,
        ),
    ]
