# Generated by Django 2.2.4 on 2019-08-30 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper_uploads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='display_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='display name'),
        ),
    ]
