# Generated by Django 2.2.5 on 2019-09-27 13:56

import django.core.files.storage
from django.db import migrations, models
import paper_uploads.models.image


class Migration(migrations.Migration):

    dependencies = [
        ('paper_uploads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileitem',
            name='file',
            field=models.FileField(max_length=255, storage=django.core.files.storage.FileSystemStorage(), upload_to='collections/files/%Y-%m-%d', verbose_name='file'),
        ),
        migrations.AlterField(
            model_name='imageitem',
            name='file',
            field=paper_uploads.models.image.VariationalFileField(max_length=255, storage=django.core.files.storage.FileSystemStorage(), upload_to='collections/images/%Y-%m-%d', verbose_name='file'),
        ),
        migrations.AlterField(
            model_name='svgitem',
            name='file',
            field=models.FileField(max_length=255, storage=django.core.files.storage.FileSystemStorage(), upload_to='collections/files/%Y-%m-%d', verbose_name='file'),
        ),
    ]
