# Generated by Django 2.2.5 on 2019-09-28 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper_uploads', '0002_auto_20190927_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileitem',
            name='name',
            field=models.CharField(editable=False, max_length=255, verbose_name='file name'),
        ),
        migrations.AlterField(
            model_name='imageitem',
            name='name',
            field=models.CharField(editable=False, max_length=255, verbose_name='file name'),
        ),
        migrations.AlterField(
            model_name='svgitem',
            name='name',
            field=models.CharField(editable=False, max_length=255, verbose_name='file name'),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='name',
            field=models.CharField(editable=False, max_length=255, verbose_name='file name'),
        ),
        migrations.AlterField(
            model_name='uploadedimage',
            name='name',
            field=models.CharField(editable=False, max_length=255, verbose_name='file name'),
        ),
    ]
