# Generated by Django 2.2.4 on 2019-08-30 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper_uploads', '0002_uploadedfile_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryfileitem',
            name='display_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='display name'),
        ),
    ]
