# Generated by Django 3.0.9 on 2020-09-07 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper_uploads', '0002_auto_20200903_1850'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fileitem',
            old_name='name',
            new_name='basename',
        ),
        migrations.RenameField(
            model_name='imageitem',
            old_name='name',
            new_name='basename',
        ),
        migrations.RenameField(
            model_name='svgitem',
            old_name='name',
            new_name='basename',
        ),
        migrations.RenameField(
            model_name='uploadedfile',
            old_name='name',
            new_name='basename',
        ),
        migrations.RenameField(
            model_name='uploadedimage',
            old_name='name',
            new_name='basename',
        ),
        migrations.AlterField(
            model_name='imageitem',
            name='description',
            field=models.TextField(blank=True, help_text='This text will be used by screen readers, search engines, or when the image cannot be loaded', verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='uploadedimage',
            name='description',
            field=models.TextField(blank=True, help_text='This text will be used by screen readers, search engines, or when the image cannot be loaded', verbose_name='description'),
        ),
    ]
