# Generated by Django 2.2.5 on 2019-09-30 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paper_uploads', '0003_auto_20190928_1226'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collectionitembase',
            old_name='object_id',
            new_name='collection_id',
        ),
    ]
