# Generated by Django 2.2.4 on 2019-09-10 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper_uploads', '0003_galleryfileitem_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallerysvgitem',
            name='display_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='display name'),
        ),
    ]
