# Generated by Django 3.0.9 on 2020-09-07 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper_uploads', '0003_auto_20200907_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileitem',
            name='basename',
            field=models.CharField(editable=False, help_text='human-readable resource name', max_length=255, verbose_name='basename'),
        ),
        migrations.AlterField(
            model_name='imageitem',
            name='basename',
            field=models.CharField(editable=False, help_text='human-readable resource name', max_length=255, verbose_name='basename'),
        ),
        migrations.AlterField(
            model_name='svgitem',
            name='basename',
            field=models.CharField(editable=False, help_text='human-readable resource name', max_length=255, verbose_name='basename'),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='basename',
            field=models.CharField(editable=False, help_text='human-readable resource name', max_length=255, verbose_name='basename'),
        ),
        migrations.AlterField(
            model_name='uploadedimage',
            name='basename',
            field=models.CharField(editable=False, help_text='human-readable resource name', max_length=255, verbose_name='basename'),
        ),
    ]
