# Generated by Django 2.2.5 on 2019-10-10 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paper_uploads', '0004_auto_20190930_1042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='cover',
        ),
    ]
