# Generated by Django 2.2.5 on 2019-09-11 12:04

from django.db import migrations


def update_owner(apps, schema_editor, reverse=False):
    """
    Update the content_type of proxy model permissions to use the ContentType
    of the proxy model.
    """
    UploadedImage = apps.get_model('paper_uploads', 'UploadedImage')
    for image in UploadedImage._meta.base_manager.all():
        image.owner_app_label = image.owner_ct.app_label
        image.owner_model_name = image.owner_ct.model
        image.save()


class Migration(migrations.Migration):

    dependencies = [
        ('paper_uploads', '0005_auto_20190911_1204'),
    ]

    operations = [
        migrations.RunPython(update_owner),
    ]
