# Generated by Django 2.2.5 on 2019-10-10 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paper_uploads', '0005_remove_collection_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionitembase',
            name='content_type',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
            preserve_default=False,
        ),
    ]
