# Generated by Django 2.2.5 on 2019-10-11 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper_uploads', '0006_auto_20191010_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileitem',
            name='extension',
            field=models.CharField(editable=False, help_text='Lowercase, without leading dot', max_length=32, verbose_name='file extension'),
        ),
        migrations.AlterField(
            model_name='imageitem',
            name='extension',
            field=models.CharField(editable=False, help_text='Lowercase, without leading dot', max_length=32, verbose_name='file extension'),
        ),
        migrations.AlterField(
            model_name='svgitem',
            name='extension',
            field=models.CharField(editable=False, help_text='Lowercase, without leading dot', max_length=32, verbose_name='file extension'),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='extension',
            field=models.CharField(editable=False, help_text='Lowercase, without leading dot', max_length=32, verbose_name='file extension'),
        ),
        migrations.AlterField(
            model_name='uploadedimage',
            name='extension',
            field=models.CharField(editable=False, help_text='Lowercase, without leading dot', max_length=32, verbose_name='file extension'),
        ),
    ]
