# Generated by Django 2.2.5 on 2019-09-11 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper_uploads', '0007_remove_uploadedimage_owner_ct'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='owner_app_label',
            field=models.CharField(default='', editable=False, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gallery',
            name='owner_model_name',
            field=models.CharField(default='', editable=False, max_length=100),
            preserve_default=False,
        ),
    ]
