# Generated by Django 2.2.6 on 2019-10-17 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paper_uploads', '0007_auto_20191011_1052'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collectionitembase',
            old_name='content_type',
            new_name='collection_content_type',
        ),
    ]
