# Generated by Django 2.2.5 on 2019-09-11 12:15

from django.db import migrations


def update_owner(apps, schema_editor, reverse=False):
    """
    Update the content_type of proxy model permissions to use the ContentType
    of the proxy model.
    """
    PageGallery = apps.get_model('app', 'PageGallery')
    for gallery in PageGallery._meta.base_manager.all():
        gallery.owner_app_label = gallery.owner_ct.app_label
        gallery.owner_model_name = gallery.owner_ct.model
        gallery.save()

    PageFilesGallery = apps.get_model('app', 'PageFilesGallery')
    for gallery in PageFilesGallery._meta.base_manager.all():
        gallery.owner_app_label = gallery.owner_ct.app_label
        gallery.owner_model_name = gallery.owner_ct.model
        gallery.save()


class Migration(migrations.Migration):

    dependencies = [
        ('paper_uploads', '0008_auto_20190911_1215'),
    ]

    operations = [
        migrations.RunPython(update_owner),
    ]
