# Generated by Django 2.2.5 on 2019-09-11 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paper_uploads', '0008_auto_20190911_1215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='owner_ct',
        ),
    ]
