# Generated by Django 2.2.6 on 2019-10-18 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper_uploads', '0008_auto_20191017_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageitem',
            name='title',
            field=models.CharField(blank=True, help_text='The title is being used as a tooltip when the user hovers the mouse over the image', max_length=255, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='uploadedimage',
            name='title',
            field=models.CharField(blank=True, help_text='The title is being used as a tooltip when the user hovers the mouse over the image', max_length=255, verbose_name='title'),
        ),
    ]
