# Generated by Django 2.2.5 on 2019-09-12 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper_uploads', '0009_remove_gallery_owner_ct'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='owner_app_label',
            field=models.CharField(default='', editable=False, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='owner_fieldname',
            field=models.CharField(default='', editable=False, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='owner_model_name',
            field=models.CharField(default='', editable=False, max_length=100),
            preserve_default=False,
        ),
    ]
