# Generated by Django 2.2.5 on 2019-09-16 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paper_uploads', '0010_auto_20190912_0854'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={},
        ),
    ]
