# Generated by Django 2.2.6 on 2019-10-25 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paper_uploads', '0011_delete_cloudinaryfile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collectionitembase',
            options={'default_permissions': (), 'verbose_name': 'item', 'verbose_name_plural': 'items'},
        ),
    ]
