# Generated by Django 2.2.5 on 2019-09-18 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper_uploads', '0011_auto_20190916_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryfileitem',
            name='extension',
            field=models.CharField(editable=False, help_text='Lowercase string without leading dot', max_length=32, verbose_name='file extension'),
        ),
        migrations.AlterField(
            model_name='galleryimageitem',
            name='extension',
            field=models.CharField(editable=False, help_text='Lowercase string without leading dot', max_length=32, verbose_name='file extension'),
        ),
        migrations.AlterField(
            model_name='gallerysvgitem',
            name='extension',
            field=models.CharField(editable=False, help_text='Lowercase string without leading dot', max_length=32, verbose_name='file extension'),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='extension',
            field=models.CharField(editable=False, help_text='Lowercase string without leading dot', max_length=32, verbose_name='file extension'),
        ),
        migrations.AlterField(
            model_name='uploadedimage',
            name='extension',
            field=models.CharField(editable=False, help_text='Lowercase string without leading dot', max_length=32, verbose_name='file extension'),
        ),
    ]
