# Generated by Django 2.2.6 on 2019-10-28 15:09

import django.core.files.storage
from django.db import migrations
import paper_uploads.models.fields.base


class Migration(migrations.Migration):

    dependencies = [
        ('paper_uploads', '0012_auto_20191025_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileitem',
            name='file',
            field=paper_uploads.models.fields.base.FormattedFileField(max_length=255, storage=django.core.files.storage.FileSystemStorage(), upload_to='collections/files/%Y-%m-%d', verbose_name='file'),
        ),
        migrations.AlterField(
            model_name='svgitem',
            name='file',
            field=paper_uploads.models.fields.base.FormattedFileField(max_length=255, storage=django.core.files.storage.FileSystemStorage(), upload_to='collections/files/%Y-%m-%d', verbose_name='file'),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='file',
            field=paper_uploads.models.fields.base.FormattedFileField(max_length=255, storage=django.core.files.storage.FileSystemStorage(), upload_to='files/%Y-%m-%d', verbose_name='file'),
        ),
    ]
