# Generated by Django 4.2.8 on 2023-12-12 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paper_uploads', '0012_fileitem_mimetype_imageitem_mimetype_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigurableImageItem',
            fields=[
            ],
            options={
                'proxy': True,
                'default_permissions': (),
                'indexes': [],
                'constraints': [],
            },
            bases=('paper_uploads.imageitem',),
        ),
    ]
