# Generated by Django 2.2.5 on 2019-09-24 13:50

import django.core.files.storage
from django.db import migrations
import django.db.models.manager
import paper_uploads.models.image


class Migration(migrations.Migration):

    dependencies = [
        ('paper_uploads', '0012_auto_20190918_1250'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'default_manager_name': 'default_mgr'},
        ),
        migrations.AlterModelManagers(
            name='gallery',
            managers=[
                ('default_mgr', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='galleryimageitem',
            name='file',
            field=paper_uploads.models.image.VariationalFileField(max_length=255, storage=django.core.files.storage.FileSystemStorage(), upload_to='gallery/images/%Y-%m-%d', verbose_name='file'),
        ),
        migrations.AlterField(
            model_name='uploadedimage',
            name='file',
            field=paper_uploads.models.image.VariationalFileField(max_length=255, storage=django.core.files.storage.FileSystemStorage(), upload_to='images/%Y-%m-%d', verbose_name='file'),
        ),
    ]
