# Generated by Django 2.2.5 on 2019-09-27 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('paper_uploads', '0013_auto_20190924_1350'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GalleryFileItem',
            new_name='FileItem',
        ),
    ]
