# Generated by Django 2.2.6 on 2019-10-31 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper_uploads', '0013_auto_20191028_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='extension',
            field=models.CharField(editable=False, help_text='Lowercase, without leading dot', max_length=32, verbose_name='extension'),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='hash',
            field=models.CharField(editable=False, help_text='SHA-1 checksum of a resource', max_length=40, verbose_name='hash'),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='name',
            field=models.CharField(editable=False, max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='size',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='size'),
        ),
    ]
