# Generated by Django 2.2.6 on 2019-11-01 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper_uploads', '0014_auto_20191031_1224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedimage',
            name='alt',
        ),
        migrations.AddField(
            model_name='uploadedimage',
            name='description',
            field=models.CharField(blank=True, help_text='This text will be used by screen readers, search engines, or when the image cannot be loaded', max_length=255, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='uploadedimage',
            name='extension',
            field=models.CharField(editable=False, help_text='Lowercase, without leading dot', max_length=32, verbose_name='extension'),
        ),
        migrations.AlterField(
            model_name='uploadedimage',
            name='hash',
            field=models.CharField(editable=False, help_text='SHA-1 checksum of a resource', max_length=40, verbose_name='hash'),
        ),
        migrations.AlterField(
            model_name='uploadedimage',
            name='name',
            field=models.CharField(editable=False, max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='uploadedimage',
            name='size',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='size'),
        ),
    ]
