# Generated by Django 2.2.6 on 2019-11-01 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paper_uploads', '0015_auto_20191101_0729'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FileItem',
        ),
        migrations.DeleteModel(
            name='SVGItem',
        ),
        migrations.DeleteModel(
            name='ImageItem',
        ),
    ]
