# Generated by Django 2.2.5 on 2019-09-27 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paper_uploads', '0016_auto_20190927_0625'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gallery',
            old_name='gallery_content_type',
            new_name='collection_content_type',
        ),
    ]
