# Generated by Django 2.2.6 on 2019-11-02 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paper_uploads', '0017_auto_20191101_1337'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fileitem',
            old_name='preview',
            new_name='preview_url',
        ),
    ]
