# Generated by Django 2.2.5 on 2019-09-27 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paper_uploads', '0017_auto_20190927_0633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='collection_content_type',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.ContentType'),
        ),
    ]
