# Generated by Django 3.0.8 on 2020-07-23 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper_uploads', '0018_auto_20191102_0731'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileitem',
            name='hash',
        ),
        migrations.RemoveField(
            model_name='imageitem',
            name='hash',
        ),
        migrations.RemoveField(
            model_name='svgitem',
            name='hash',
        ),
        migrations.RemoveField(
            model_name='uploadedfile',
            name='hash',
        ),
        migrations.RemoveField(
            model_name='uploadedimage',
            name='hash',
        ),
        migrations.AddField(
            model_name='fileitem',
            name='content_hash',
            field=models.CharField(default='', editable=False, help_text='hash of the contents of a file', max_length=64, verbose_name='content hash'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imageitem',
            name='content_hash',
            field=models.CharField(default='', editable=False, help_text='hash of the contents of a file', max_length=64, verbose_name='content hash'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='svgitem',
            name='content_hash',
            field=models.CharField(default='', editable=False, help_text='hash of the contents of a file', max_length=64, verbose_name='content hash'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='content_hash',
            field=models.CharField(default='', editable=False, help_text='hash of the contents of a file', max_length=64, verbose_name='content hash'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uploadedimage',
            name='content_hash',
            field=models.CharField(default='', editable=False, help_text='hash of the contents of a file', max_length=64, verbose_name='content hash'),
            preserve_default=False,
        ),
    ]
