# Generated by Django 3.0.8 on 2020-07-23 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper_uploads', '0019_auto_20200723_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileitem',
            name='name',
            field=models.CharField(editable=False, help_text='human readable resource name', max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='imageitem',
            name='name',
            field=models.CharField(editable=False, help_text='human readable resource name', max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='svgitem',
            name='name',
            field=models.CharField(editable=False, help_text='human readable resource name', max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='name',
            field=models.CharField(editable=False, help_text='human readable resource name', max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='uploadedimage',
            name='name',
            field=models.CharField(editable=False, help_text='human readable resource name', max_length=255, verbose_name='name'),
        ),
    ]
