# Generated by Django 3.2.9 on 2021-12-09 10:05

from django.db import migrations
import django.db.models.deletion
import paper_uploads.models.fields.image
import paper_uploads.validators


class Migration(migrations.Migration):

    dependencies = [
        ('paper_uploads', '0007_alter_collection_options'),
        ('validators', '0002_page_filter_image_ext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='filter_image_ext',
            field=paper_uploads.models.fields.image.ImageField(blank=True, help_text='Only `png` and `gif` allowed', on_delete=django.db.models.deletion.SET_NULL, to='paper_uploads.uploadedimage', validators=[paper_uploads.validators.ExtensionValidator(['.gif', '.png'])], verbose_name='extension (image)'),
        ),
    ]
