# Generated by Django 4.0.2 on 2022-02-09 05:39

from django.db import migrations
import django.db.models.deletion
import paper_uploads.models.fields.file
import paper_uploads.validators


class Migration(migrations.Migration):

    dependencies = [
        ('paper_uploads', '0001_squashed_0009_alter_collectionitembase_polymorphic_ctype_and_more'),
        ('validators', '0003_alter_page_filter_image_ext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='filter_size',
            field=paper_uploads.models.fields.file.FileField(blank=True, help_text='Maximum file size is 16Kb', on_delete=django.db.models.deletion.SET_NULL, storage=None, to='paper_uploads.uploadedfile', upload_to='', validators=[paper_uploads.validators.MaxSizeValidator('16kb')], verbose_name='size'),
        ),
    ]
