# Generated by Django 4.0.1 on 2022-02-14 07:01

from django.db import migrations
import django.db.models.deletion
import paper_uploads.cloudinary.models.fields.media


class Migration(migrations.Migration):

    dependencies = [
        ('paper_uploads_cloudinary', '0005_auto_20211116_0840'),
        ('standard_cloudinary_fields', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='media',
            field=paper_uploads.cloudinary.models.fields.media.CloudinaryMediaField(blank=True, on_delete=django.db.models.deletion.SET_NULL, storage=None, to='paper_uploads_cloudinary.cloudinarymedia', upload_to='', verbose_name='image'),
        ),
    ]
