# Generated by Django 3.0.9 on 2020-08-30 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paper_uploads_cloudinary', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cloudinaryfileitem',
            name='file',
        ),
        migrations.RemoveField(
            model_name='cloudinaryimage',
            name='file',
        ),
        migrations.RemoveField(
            model_name='cloudinaryimageitem',
            name='file',
        ),
        migrations.RemoveField(
            model_name='cloudinarymedia',
            name='file',
        ),
        migrations.RemoveField(
            model_name='cloudinarymediaitem',
            name='file',
        ),
    ]
