# Generated by Django 3.0.9 on 2020-09-01 06:57

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paper_uploads_cloudinary', '0002_auto_20200830_0600'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloudinarymedia',
            name='file',
            field=cloudinary.models.CloudinaryField(default=None, max_length=255, verbose_name='file'),
            preserve_default=False,
        ),
    ]
