# Generated by Django 3.0.8 on 2020-07-23 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper_uploads_cloudinary', '0002_cloudinarycollection_cloudinaryfileitem_cloudinaryimagecollection_cloudinaryimageitem_cloudinarymedi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cloudinaryfile',
            name='hash',
        ),
        migrations.RemoveField(
            model_name='cloudinaryfileitem',
            name='hash',
        ),
        migrations.RemoveField(
            model_name='cloudinaryimage',
            name='hash',
        ),
        migrations.RemoveField(
            model_name='cloudinaryimageitem',
            name='hash',
        ),
        migrations.RemoveField(
            model_name='cloudinarymedia',
            name='hash',
        ),
        migrations.RemoveField(
            model_name='cloudinarymediaitem',
            name='hash',
        ),
        migrations.AddField(
            model_name='cloudinaryfile',
            name='content_hash',
            field=models.CharField(default='', editable=False, help_text='hash of the contents of a file', max_length=64, verbose_name='content hash'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cloudinaryfileitem',
            name='content_hash',
            field=models.CharField(default='', editable=False, help_text='hash of the contents of a file', max_length=64, verbose_name='content hash'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cloudinaryimage',
            name='content_hash',
            field=models.CharField(default='', editable=False, help_text='hash of the contents of a file', max_length=64, verbose_name='content hash'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cloudinaryimageitem',
            name='content_hash',
            field=models.CharField(default='', editable=False, help_text='hash of the contents of a file', max_length=64, verbose_name='content hash'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cloudinarymedia',
            name='content_hash',
            field=models.CharField(default='', editable=False, help_text='hash of the contents of a file', max_length=64, verbose_name='content hash'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cloudinarymediaitem',
            name='content_hash',
            field=models.CharField(default='', editable=False, help_text='hash of the contents of a file', max_length=64, verbose_name='content hash'),
            preserve_default=False,
        ),
    ]
