# Generated by Django 3.0.8 on 2020-07-23 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper_uploads_cloudinary', '0003_auto_20200723_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloudinaryfile',
            name='name',
            field=models.CharField(editable=False, help_text='human readable resource name', max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='cloudinaryfileitem',
            name='name',
            field=models.CharField(editable=False, help_text='human readable resource name', max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='cloudinaryimage',
            name='name',
            field=models.CharField(editable=False, help_text='human readable resource name', max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='cloudinaryimageitem',
            name='name',
            field=models.CharField(editable=False, help_text='human readable resource name', max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='cloudinarymedia',
            name='name',
            field=models.CharField(editable=False, help_text='human readable resource name', max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='cloudinarymediaitem',
            name='name',
            field=models.CharField(editable=False, help_text='human readable resource name', max_length=255, verbose_name='name'),
        ),
    ]
