# Generated by Django 2.2.6 on 2019-10-25 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paper_uploads_cloudinary', '0003_auto_20191025_0452'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CloudinaryVideo',
            new_name='CloudinaryMedia',
        ),
    ]
