# Generated by Django 3.0.9 on 2020-09-01 07:56

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paper_uploads_cloudinary', '0003_cloudinarymedia_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloudinaryimage',
            name='file',
            field=cloudinary.models.CloudinaryField(default=None, max_length=255, verbose_name='file'),
            preserve_default=False,
        ),
    ]
