# Generated by Django 3.0.9 on 2020-09-02 04:59

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paper_uploads_cloudinary', '0004_cloudinaryimage_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cloudinaryfileitem',
            options={'verbose_name': 'File item', 'verbose_name_plural': 'File items'},
        ),
        migrations.AlterModelOptions(
            name='cloudinaryimageitem',
            options={'verbose_name': 'Image item', 'verbose_name_plural': 'Image items'},
        ),
        migrations.AlterModelOptions(
            name='cloudinarymediaitem',
            options={'verbose_name': 'Media item', 'verbose_name_plural': 'Media items'},
        ),
        migrations.AddField(
            model_name='cloudinaryfileitem',
            name='file',
            field=cloudinary.models.CloudinaryField(default=None, max_length=255, verbose_name='file'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cloudinaryimageitem',
            name='file',
            field=cloudinary.models.CloudinaryField(default=None, max_length=255, verbose_name='file'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cloudinarymediaitem',
            name='file',
            field=cloudinary.models.CloudinaryField(default=None, max_length=255, verbose_name='file'),
            preserve_default=False,
        ),
    ]
