# Generated by Django 3.0.9 on 2020-09-03 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper_uploads_cloudinary', '0005_auto_20200902_0459'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cloudinaryfile',
            name='content_hash',
        ),
        migrations.RemoveField(
            model_name='cloudinaryfileitem',
            name='content_hash',
        ),
        migrations.RemoveField(
            model_name='cloudinaryimage',
            name='content_hash',
        ),
        migrations.RemoveField(
            model_name='cloudinaryimageitem',
            name='content_hash',
        ),
        migrations.RemoveField(
            model_name='cloudinarymedia',
            name='content_hash',
        ),
        migrations.RemoveField(
            model_name='cloudinarymediaitem',
            name='content_hash',
        ),
        migrations.AddField(
            model_name='cloudinaryfile',
            name='checksum',
            field=models.CharField(default='', editable=False, max_length=64, verbose_name='checksum'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cloudinaryfileitem',
            name='checksum',
            field=models.CharField(default='', editable=False, max_length=64, verbose_name='checksum'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cloudinaryimage',
            name='checksum',
            field=models.CharField(default='', editable=False, max_length=64, verbose_name='checksum'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cloudinaryimageitem',
            name='checksum',
            field=models.CharField(default='', editable=False, max_length=64, verbose_name='checksum'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cloudinarymedia',
            name='checksum',
            field=models.CharField(default='', editable=False, max_length=64, verbose_name='checksum'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cloudinarymediaitem',
            name='checksum',
            field=models.CharField(default='', editable=False, max_length=64, verbose_name='checksum'),
            preserve_default=False,
        ),
    ]
