# Generated by Django 2.2.6 on 2019-10-28 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paper_uploads_cloudinary', '0005_cloudinaryfileitem_cloudinaryimagecollection_cloudinaryimageitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cloudinaryfileitem',
            options={'base_manager_name': 'objects', 'verbose_name': 'file', 'verbose_name_plural': 'files'},
        ),
    ]
