# Generated by Django 4.0.1 on 2022-02-16 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper_uploads_cloudinary', '0006_rename_basename_cloudinaryfile_resource_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloudinaryfile',
            name='resource_name',
            field=models.CharField(editable=False, help_text='Human-readable resource name', max_length=255, verbose_name='resource name'),
        ),
        migrations.AlterField(
            model_name='cloudinaryfileitem',
            name='resource_name',
            field=models.CharField(editable=False, help_text='Human-readable resource name', max_length=255, verbose_name='resource name'),
        ),
        migrations.AlterField(
            model_name='cloudinaryimage',
            name='resource_name',
            field=models.CharField(editable=False, help_text='Human-readable resource name', max_length=255, verbose_name='resource name'),
        ),
        migrations.AlterField(
            model_name='cloudinaryimageitem',
            name='resource_name',
            field=models.CharField(editable=False, help_text='Human-readable resource name', max_length=255, verbose_name='resource name'),
        ),
        migrations.AlterField(
            model_name='cloudinarymedia',
            name='resource_name',
            field=models.CharField(editable=False, help_text='Human-readable resource name', max_length=255, verbose_name='resource name'),
        ),
        migrations.AlterField(
            model_name='cloudinarymediaitem',
            name='resource_name',
            field=models.CharField(editable=False, help_text='Human-readable resource name', max_length=255, verbose_name='resource name'),
        ),
    ]
