# Generated by Django 2.2.6 on 2019-10-28 08:34

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paper_uploads_cloudinary', '0006_auto_20191028_0817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloudinaryimageitem',
            name='file',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='file'),
        ),
    ]
