# Generated by Django 3.0.9 on 2020-09-07 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper_uploads_cloudinary', '0007_auto_20200907_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloudinaryfile',
            name='basename',
            field=models.CharField(editable=False, help_text='human-readable resource name', max_length=255, verbose_name='basename'),
        ),
        migrations.AlterField(
            model_name='cloudinaryfileitem',
            name='basename',
            field=models.CharField(editable=False, help_text='human-readable resource name', max_length=255, verbose_name='basename'),
        ),
        migrations.AlterField(
            model_name='cloudinaryimage',
            name='basename',
            field=models.CharField(editable=False, help_text='human-readable resource name', max_length=255, verbose_name='basename'),
        ),
        migrations.AlterField(
            model_name='cloudinaryimageitem',
            name='basename',
            field=models.CharField(editable=False, help_text='human-readable resource name', max_length=255, verbose_name='basename'),
        ),
        migrations.AlterField(
            model_name='cloudinarymedia',
            name='basename',
            field=models.CharField(editable=False, help_text='human-readable resource name', max_length=255, verbose_name='basename'),
        ),
        migrations.AlterField(
            model_name='cloudinarymediaitem',
            name='basename',
            field=models.CharField(editable=False, help_text='human-readable resource name', max_length=255, verbose_name='basename'),
        ),
    ]
