# Generated by Django 3.2.9 on 2021-12-08 10:31

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('custom_collection', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomSubCollection',
            fields=[
            ],
            options={
                'proxy': True,
                'default_permissions': (),
                'indexes': [],
                'constraints': [],
            },
            bases=('custom_collection.customcollection',),
            managers=[
                ('default_mgr', django.db.models.manager.Manager()),
            ],
        ),
    ]
