# Generated by Django 3.2.9 on 2021-12-02 18:20

from django.db import migrations, models
import django.db.models.deletion
import paper_uploads.models.fields.file
import paper_uploads.models.fields.image


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('paper_uploads', '0006_auto_20211116_0748'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFileProxy',
            fields=[
            ],
            options={
                'proxy': True,
                'default_permissions': (),
                'indexes': [],
                'constraints': [],
            },
            bases=('paper_uploads.uploadedfile',),
        ),
        migrations.CreateModel(
            name='UploadedImageProxy',
            fields=[
            ],
            options={
                'proxy': True,
                'default_permissions': (),
                'indexes': [],
                'constraints': [],
            },
            bases=('paper_uploads.uploadedimage',),
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', paper_uploads.models.fields.file.FileField(blank=True, on_delete=django.db.models.deletion.SET_NULL, to='proxy_files.uploadedfileproxy', verbose_name='file')),
                ('image', paper_uploads.models.fields.image.ImageField(blank=True, on_delete=django.db.models.deletion.SET_NULL, to='proxy_files.uploadedimageproxy', verbose_name='image')),
            ],
            options={
                'verbose_name': 'Page',
            },
        ),
    ]
