name: Deploy

on:
  push:
    tags:
      - v*

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '15'
      - name: Install dependencies
        run: |
          python -m pip install setuptools==60.10.0
          python -m pip install --upgrade pip wheel twine
      - name: Install NPM dependencies
        run: npm ci
      - name: Run webpack
        run: npx webpack --mode=production
      - name: Build and publish
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          python setup.py sdist bdist_wheel
          twine check dist/*
          twine upload dist/*
